//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWCApp.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoughtItemDetail
    {
        public int DetailsId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> ShopOwnerId { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ContactNo { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> WholeSalePrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
