//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWCApp.Data.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CWCAppDBEntities : DbContext
    {
        public CWCAppDBEntities()
            : base("name=CWCAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ServiceProviderMstr> ServiceProviderMstrs { get; set; }
        public virtual DbSet<ServiceProviderProfile> ServiceProviderProfiles { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserTypeMstr> UserTypeMstrs { get; set; }
        public virtual DbSet<ShoppingMethodMstr> ShoppingMethodMstrs { get; set; }
        public virtual DbSet<VehiclePartsStore> VehiclePartsStores { get; set; }
        public virtual DbSet<VehiclePartsStoreItem> VehiclePartsStoreItems { get; set; }
        public virtual DbSet<BoughtItemDetail> BoughtItemDetails { get; set; }
        public virtual DbSet<Garage> Garages { get; set; }
        public virtual DbSet<TOWService> TOWServices { get; set; }
        public virtual DbSet<RequestedTOWDetail> RequestedTOWDetails { get; set; }
        public virtual DbSet<RepairService> RepairServices { get; set; }
        public virtual DbSet<RequestedRepairDetail> RequestedRepairDetails { get; set; }
        public virtual DbSet<VehicleRentalService> VehicleRentalServices { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
        public virtual DbSet<ServiceFeedBack> ServiceFeedBacks { get; set; }
        public virtual DbSet<RequestedRentalDetail> RequestedRentalDetails { get; set; }
    }
}
