//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWCApp.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garage
    {
        public int GarageId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string GarageName { get; set; }
        public string AddressOfGarage { get; set; }
        public string VehicleCapacity { get; set; }
        public Nullable<decimal> TOWCapability { get; set; }
        public Nullable<decimal> TOWPayload { get; set; }
        public Nullable<int> NumberOfMechanics { get; set; }
        public string RangeOfService { get; set; }
        public string ExtraFeatures { get; set; }
        public string PictureOfGarage { get; set; }
        public string Rates { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
