//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWCApp.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public int RateId { get; set; }
        public Nullable<int> RatedUserId { get; set; }
        public Nullable<int> ServiceProviderId { get; set; }
        public Nullable<int> ServiceProviderType { get; set; }
        public Nullable<int> ProductOrServiceId { get; set; }
        public Nullable<decimal> RatedValue { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
