//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWCApp.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingMethodMstr
    {
        public int ShoppingMethodId { get; set; }
        public string ShoppingMethod { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
