//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWCApp.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOWService
    {
        public int TOWServiceID { get; set; }
        public Nullable<int> GarageId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TypeOfVehicleOwn { get; set; }
        public Nullable<decimal> MaxPayLoad { get; set; }
        public Nullable<int> NoOfVehicleOwn { get; set; }
        public Nullable<decimal> RatePerKm { get; set; }
        public string RangeOfService { get; set; }
        public string ExtraFeatures { get; set; }
        public string VehicleImage { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
