//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWCApp.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclePartsStoreItem
    {
        public int ItemId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public Nullable<int> ItemTotalAmount { get; set; }
        public Nullable<int> ItemBoughtAmount { get; set; }
        public Nullable<int> ItemBalance { get; set; }
        public string ItemBrand { get; set; }
        public string ItemImage { get; set; }
        public string ItemDiscription { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> WholeSalePrice { get; set; }
        public string ItemSpecs { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
