//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWCApp.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclePartsStore
    {
        public int StoreId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string StoreName { get; set; }
        public string ContactNumber { get; set; }
        public string AddressOfStore { get; set; }
        public Nullable<int> ShoppingMethod { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
